name: Mirror Docker Image

on:
  schedule:
    - cron: '0 23 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:      # Allows manual trigger

permissions:
  packages: write        # Add permissions to write packages
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull and push Docker images
        run: |
          # Define array of Docker repositories
          DOCKER_REPOS=(
            "lobehub/lobe-chat-database"
            "lobehub/lobe-chat"
            "tiredofit/db-backup"
          )

          # Loop through each repository
          for REPO in "${DOCKER_REPOS[@]}"; do
            # Extract repository name for use in GHCR path
            REPO_NAME=$(echo $REPO | cut -d'/' -f2)
            
            # Get the most recent version tag (excluding 'latest')
            LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/$REPO/tags?page_size=2" | jq -r '.results[].name' | grep -v '^latest$' | sort -V | tail -n1)
            
            echo "Processing repository: $REPO"
            echo "Latest version tag: $LATEST_TAG"
            
            # Pull and push the latest version
            docker pull "$REPO:$LATEST_TAG"
            docker tag "$REPO:$LATEST_TAG" "ghcr.io/${{ github.repository_owner }}/$REPO_NAME:$LATEST_TAG"
            docker push "ghcr.io/${{ github.repository_owner }}/$REPO_NAME:$LATEST_TAG"
            docker push "ghcr.io/${{ github.repository_owner }}/$REPO_NAME:latest"
            
            echo "Completed processing $REPO"
            echo "-------------------"
          done
