name: Mirror Docker Image

on:
  schedule:
    - cron: '0 23 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:      # Allows manual trigger

permissions:
  packages: write        # Add permissions to write packages
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Pull and push Docker image
        run: |
          # Get the most recent version tag (excluding 'latest')
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/lobehub/lobe-chat-database/tags?page_size=2" | jq -r '.results[].name' | grep -v '^latest$' | sort -V | tail -n1)
          
          echo "Latest version tag: $LATEST_TAG"
          
          # Pull and push the latest version
          docker pull "lobehub/lobe-chat-database:$LATEST_TAG"
          docker tag "lobehub/lobe-chat-database:$LATEST_TAG" "ghcr.io/${{ github.repository_owner }}/lobe-chat-database:$LATEST_TAG"
          docker push "ghcr.io/${{ github.repository_owner }}/lobe-chat-database:$LATEST_TAG"